----========================================================================================================================----
----===----------------------------------------------Generator bazy danych-----------------------------------------------===----
----========================================================================================================================----
@Tables/Physical_Tables.sql
@Tables/Views.sql
@Generators/Generate_Hashes.sql
@Generators/Generate_Logins.sql
@Generators/Generate_Men_Lasts.sql
@Generators/Generate_Men_Names.sql
@Generators/Generate_Men_Posts.sql
@Generators/Generate_Passwords.sql
@Generators/Generate_Pools_Names.sql
@Generators/Generate_Services.sql
@Generators/Generate_Streets.sql
@Generators/Generate_Towns.sql
@Generators/Generate_Women_Lasts.sql
@Generators/Generate_Women_Names.sql
@Generators/Generate_Women_Posts.sql
@Procedures/Generate_Auditors.sql
@Procedures/Generate_Clients.sql
@Procedures/Generate_Inspections.sql
@Procedures/Generate_Lessons_Reservations.sql
@Procedures/Generate_Owners.sql
@Procedures/Generate_Pools.sql
@Procedures/Generate_Posts.sql
@Procedures/Generate_Services.sql
@Procedures/Generate_Transactions.sql
@Procedures/Generate_Workers.sql
@Populate.sql