  CREATE TABLE GENERATOR_WOMEN_POSTS 
   (	"STANOWISKO" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUSINESS" ;
REM INSERTING into GENERATOR_WOMEN_POSTS
SET DEFINE OFF;
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('ekspertka ds. marketingu');
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('HR');
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('kasjerka');
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('kierowniczka');
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('konserwatorka');
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('ratowniczka');
Insert into GENERATOR_WOMEN_POSTS (STANOWISKO) values ('sprz¹taczka');