  CREATE TABLE GENERATOR_MEN_LASTS 
   (	"NAZWISKO" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUSINESS" ;
REM INSERTING into GENERATOR_MEN_LASTS
SET DEFINE OFF;
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('NOWAK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KOWALSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WIåNIEWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('W”JCIK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KOWALCZYK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KAMI—SKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('LEWANDOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('D•BROWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('ZIELI—SKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('SZYMA—SKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WOèNIAK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KOZ£OWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('JANKOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('MAZUR');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WOJCIECHOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KWIATKOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KRAWCZYK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KACZMAREK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('PIOTROWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('GRABOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('ZAJ•C');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('PAW£OWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('MICHALSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('KR”L');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('NOWAKOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WIECZOREK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WR”BEL');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('JAB£O—SKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('DUDEK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('ADAMCZYK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('MAJEWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('NOWICKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('OLSZEWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('ST PIE—');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('JAWORSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('MALINOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('PAWLAK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('G”RSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WITKOWSKI');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('WALCZAK');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('SIKORA');
Insert into GENERATOR_MEN_LASTS (NAZWISKO) values ('RUTKOWSKI');