  CREATE TABLE GENERATOR_TOWNS 
   (	"MIASTO" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUSINESS" ;
REM INSERTING into GENERATOR_TOWNS
SET DEFINE OFF;
Insert into GENERATOR_TOWNS (MIASTO) values ('Warszawa');
Insert into GENERATOR_TOWNS (MIASTO) values ('Kraków');
Insert into GENERATOR_TOWNS (MIASTO) values ('Kielce');
Insert into GENERATOR_TOWNS (MIASTO) values ('Gdañsk');
Insert into GENERATOR_TOWNS (MIASTO) values ('Bia³ystok');
Insert into GENERATOR_TOWNS (MIASTO) values ('Szczecin');
Insert into GENERATOR_TOWNS (MIASTO) values ('Katowice');
Insert into GENERATOR_TOWNS (MIASTO) values ('Zakopane');
Insert into GENERATOR_TOWNS (MIASTO) values ('Lublin');
Insert into GENERATOR_TOWNS (MIASTO) values ('Toruñ');
Insert into GENERATOR_TOWNS (MIASTO) values ('Bydgoszcz');
Insert into GENERATOR_TOWNS (MIASTO) values ('Czêstochowa');