  CREATE TABLE GENERATOR_SERVICES 
   (	"USLUGA" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUSINESS" ;
REM INSERTING into GENERATOR_SERVICES
SET DEFINE OFF;
Insert into GENERATOR_SERVICES (USLUGA) values ('karnet');
Insert into GENERATOR_SERVICES (USLUGA) values ('bilet normalny');
Insert into GENERATOR_SERVICES (USLUGA) values ('bilet ulgowy');
Insert into GENERATOR_SERVICES (USLUGA) values ('masa¿');
Insert into GENERATOR_SERVICES (USLUGA) values ('sauna');
Insert into GENERATOR_SERVICES (USLUGA) values ('termy');
Insert into GENERATOR_SERVICES (USLUGA) values ('aerobik');
Insert into GENERATOR_SERVICES (USLUGA) values ('rezerwacja toru');
Insert into GENERATOR_SERVICES (USLUGA) values ('lekcja p³ywania');
Insert into GENERATOR_SERVICES (USLUGA) values ('squash');