  CREATE TABLE GENERATOR_WOMEN_LASTS 
   (	"NAZWISKO" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUSINESS" ;
REM INSERTING into GENERATOR_WOMEN_LASTS
SET DEFINE OFF;
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('NOWAK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KOWALSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WIåNIEWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('W”JCIK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KOWALCZYK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KAMI—SKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('LEWANDOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('D•BROWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('ZIELI—SKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('SZYMA—SKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WOèNIAK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KOZ£OWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('JANKOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WOJCIECHOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KWIATKOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('MAZUR');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KRAWCZYK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('PIOTROWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KACZMAREK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('GRABOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('PAW£OWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('MICHALSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('ZAJ•C');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('KR”L');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('NOWAKOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WIECZOREK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('JAB£O—SKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('MAJEWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('ADAMCZYK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WR”BEL');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('NOWICKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('DUDEK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('OLSZEWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('JAWORSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('MALINOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('ST PIE—');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('G”RSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('PAWLAK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WITKOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('WALCZAK');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('RUTKOWSKA');
Insert into GENERATOR_WOMEN_LASTS (NAZWISKO) values ('SIKORA');