  CREATE TABLE GENERATOR_LOGINS 
   (	"LOGIN" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BUSINESS" ;
REM INSERTING into GENERATOR_LOGINS
SET DEFINE OFF;
Insert into GENERATOR_LOGINS (LOGIN) values ('sikiksokuk');
Insert into GENERATOR_LOGINS (LOGIN) values ('lopascslt');
Insert into GENERATOR_LOGINS (LOGIN) values ('006116.h');
Insert into GENERATOR_LOGINS (LOGIN) values ('t2053951');
Insert into GENERATOR_LOGINS (LOGIN) values ('12123333aa');
Insert into GENERATOR_LOGINS (LOGIN) values ('axrobos112');
Insert into GENERATOR_LOGINS (LOGIN) values ('s0zk0d55b');
Insert into GENERATOR_LOGINS (LOGIN) values ('nat0141');
Insert into GENERATOR_LOGINS (LOGIN) values ('kutklauw20');
Insert into GENERATOR_LOGINS (LOGIN) values ('Hi77v14w');
Insert into GENERATOR_LOGINS (LOGIN) values ('dre85lol96');
Insert into GENERATOR_LOGINS (LOGIN) values ('djodjo6363');
Insert into GENERATOR_LOGINS (LOGIN) values ('wousje88');
Insert into GENERATOR_LOGINS (LOGIN) values ('867792503');
Insert into GENERATOR_LOGINS (LOGIN) values ('Biggame05');
Insert into GENERATOR_LOGINS (LOGIN) values ('officermad');
Insert into GENERATOR_LOGINS (LOGIN) values ('sgh1404');
Insert into GENERATOR_LOGINS (LOGIN) values ('osbpass1');
Insert into GENERATOR_LOGINS (LOGIN) values ('jokegon123');
Insert into GENERATOR_LOGINS (LOGIN) values ('sght561');
Insert into GENERATOR_LOGINS (LOGIN) values ('awdsef183');
Insert into GENERATOR_LOGINS (LOGIN) values ('i7r1u3qh');
Insert into GENERATOR_LOGINS (LOGIN) values ('gfdiegfdie');
Insert into GENERATOR_LOGINS (LOGIN) values ('obuda224');
Insert into GENERATOR_LOGINS (LOGIN) values ('zachnelle');
Insert into GENERATOR_LOGINS (LOGIN) values ('rautila96');
Insert into GENERATOR_LOGINS (LOGIN) values ('limbo9090');
Insert into GENERATOR_LOGINS (LOGIN) values ('0507561378');
Insert into GENERATOR_LOGINS (LOGIN) values ('tr33l0rd');
Insert into GENERATOR_LOGINS (LOGIN) values ('dzoha1');
Insert into GENERATOR_LOGINS (LOGIN) values ('uwotm9xo');
Insert into GENERATOR_LOGINS (LOGIN) values ('13937894r');
Insert into GENERATOR_LOGINS (LOGIN) values ('avoxiam');
Insert into GENERATOR_LOGINS (LOGIN) values ('whiplon1');
Insert into GENERATOR_LOGINS (LOGIN) values ('03009026');
Insert into GENERATOR_LOGINS (LOGIN) values ('tisirambo1');
Insert into GENERATOR_LOGINS (LOGIN) values ('3e8i5t1q');
Insert into GENERATOR_LOGINS (LOGIN) values ('osbpass1');
Insert into GENERATOR_LOGINS (LOGIN) values ('renearon7');
Insert into GENERATOR_LOGINS (LOGIN) values ('jkhgkfg');
Insert into GENERATOR_LOGINS (LOGIN) values ('Motokov1p');
Insert into GENERATOR_LOGINS (LOGIN) values ('Bigbob9796');
Insert into GENERATOR_LOGINS (LOGIN) values ('gsdgdsfsd');
Insert into GENERATOR_LOGINS (LOGIN) values ('awdsef183');
Insert into GENERATOR_LOGINS (LOGIN) values ('Chrissysue');
Insert into GENERATOR_LOGINS (LOGIN) values ('1233456?');
Insert into GENERATOR_LOGINS (LOGIN) values ('aserfwe');
Insert into GENERATOR_LOGINS (LOGIN) values ('bkrox28');
Insert into GENERATOR_LOGINS (LOGIN) values ('s imon');
Insert into GENERATOR_LOGINS (LOGIN) values ('youanmde');
Insert into GENERATOR_LOGINS (LOGIN) values ('yfibc47m');
Insert into GENERATOR_LOGINS (LOGIN) values ('hiker552');
Insert into GENERATOR_LOGINS (LOGIN) values ('osbpass1');
Insert into GENERATOR_LOGINS (LOGIN) values ('erazes nan');
Insert into GENERATOR_LOGINS (LOGIN) values ('dcqg0k87');
Insert into GENERATOR_LOGINS (LOGIN) values ('270564ma');
Insert into GENERATOR_LOGINS (LOGIN) values ('Knekas49');
Insert into GENERATOR_LOGINS (LOGIN) values ('20.23');
Insert into GENERATOR_LOGINS (LOGIN) values ('hfwpr6hzrk');
Insert into GENERATOR_LOGINS (LOGIN) values ('L@ve6969');
Insert into GENERATOR_LOGINS (LOGIN) values ('Rch29197');
Insert into GENERATOR_LOGINS (LOGIN) values ('awdsef183');
Insert into GENERATOR_LOGINS (LOGIN) values ('s0zk0d55b');
Insert into GENERATOR_LOGINS (LOGIN) values ('pootrock14');
Insert into GENERATOR_LOGINS (LOGIN) values ('rahamasin');
Insert into GENERATOR_LOGINS (LOGIN) values ('rlr2k');
Insert into GENERATOR_LOGINS (LOGIN) values ('ccdd97ww');
Insert into GENERATOR_LOGINS (LOGIN) values ('7ren9Zi6qV');
Insert into GENERATOR_LOGINS (LOGIN) values ('zeusk0s1');
Insert into GENERATOR_LOGINS (LOGIN) values ('spikie1507');
Insert into GENERATOR_LOGINS (LOGIN) values ('Qn19Qn19');
Insert into GENERATOR_LOGINS (LOGIN) values ('Margie1996');
Insert into GENERATOR_LOGINS (LOGIN) values ('sPaule66');
Insert into GENERATOR_LOGINS (LOGIN) values ('ohfom3uv');
Insert into GENERATOR_LOGINS (LOGIN) values ('Gsm2691');
Insert into GENERATOR_LOGINS (LOGIN) values ('Louis32497');
Insert into GENERATOR_LOGINS (LOGIN) values ('e1e2t3u4');
Insert into GENERATOR_LOGINS (LOGIN) values ('napisdik');
Insert into GENERATOR_LOGINS (LOGIN) values ('awdsef183');
Insert into GENERATOR_LOGINS (LOGIN) values ('Alex93933');
Insert into GENERATOR_LOGINS (LOGIN) values ('104106008');
Insert into GENERATOR_LOGINS (LOGIN) values ('tisirambo1');
Insert into GENERATOR_LOGINS (LOGIN) values ('Chad0313');
Insert into GENERATOR_LOGINS (LOGIN) values ('matkosimai');
Insert into GENERATOR_LOGINS (LOGIN) values ('mamaloe1');
Insert into GENERATOR_LOGINS (LOGIN) values ('amonchao');
Insert into GENERATOR_LOGINS (LOGIN) values ('139MGtest');
Insert into GENERATOR_LOGINS (LOGIN) values ('gosh ali');
Insert into GENERATOR_LOGINS (LOGIN) values ('Kello1988');
Insert into GENERATOR_LOGINS (LOGIN) values ('styvukas');
Insert into GENERATOR_LOGINS (LOGIN) values ('PrP8c7at');
Insert into GENERATOR_LOGINS (LOGIN) values ('s9de6sw1s1');
Insert into GENERATOR_LOGINS (LOGIN) values ('eitmhpbv');
Insert into GENERATOR_LOGINS (LOGIN) values ('anotatos');
Insert into GENERATOR_LOGINS (LOGIN) values ('CCS93');
Insert into GENERATOR_LOGINS (LOGIN) values ('sikim1988');
Insert into GENERATOR_LOGINS (LOGIN) values ('Fu9o3i05');
Insert into GENERATOR_LOGINS (LOGIN) values ('dane123;');
Insert into GENERATOR_LOGINS (LOGIN) values ('s9de6sw1s1');
Insert into GENERATOR_LOGINS (LOGIN) values ('sidgon+007');
Insert into GENERATOR_LOGINS (LOGIN) values ('110228650');
Insert into GENERATOR_LOGINS (LOGIN) values ('2707ns');
Insert into GENERATOR_LOGINS (LOGIN) values ('lighterx1');
Insert into GENERATOR_LOGINS (LOGIN) values ('bigbruda');
Insert into GENERATOR_LOGINS (LOGIN) values ('vinitalt2');
Insert into GENERATOR_LOGINS (LOGIN) values ('amchazboy');
Insert into GENERATOR_LOGINS (LOGIN) values ('FeR12345');
Insert into GENERATOR_LOGINS (LOGIN) values ('said2003');
Insert into GENERATOR_LOGINS (LOGIN) values ('ntysir');
Insert into GENERATOR_LOGINS (LOGIN) values ('s sir');
Insert into GENERATOR_LOGINS (LOGIN) values ('Qve5z1');
Insert into GENERATOR_LOGINS (LOGIN) values ('uwotm9xo');
Insert into GENERATOR_LOGINS (LOGIN) values ('fatmum22');
Insert into GENERATOR_LOGINS (LOGIN) values ('charsit');
Insert into GENERATOR_LOGINS (LOGIN) values ('trwetert');
Insert into GENERATOR_LOGINS (LOGIN) values ('doo9n');
Insert into GENERATOR_LOGINS (LOGIN) values ('sikim1988');
Insert into GENERATOR_LOGINS (LOGIN) values ('man21W');
Insert into GENERATOR_LOGINS (LOGIN) values ('lewieb1989');
Insert into GENERATOR_LOGINS (LOGIN) values ('mboutrecht');
Insert into GENERATOR_LOGINS (LOGIN) values ('kingenjale');
Insert into GENERATOR_LOGINS (LOGIN) values ('MwMw2Mw3Mw4');
Insert into GENERATOR_LOGINS (LOGIN) values ('wpluttrell7896');
Insert into GENERATOR_LOGINS (LOGIN) values ('139MGtest');
Insert into GENERATOR_LOGINS (LOGIN) values ('b0z3p13m3ltj3');
Insert into GENERATOR_LOGINS (LOGIN) values ('snapordie32');
Insert into GENERATOR_LOGINS (LOGIN) values ('pissikissi01231');
Insert into GENERATOR_LOGINS (LOGIN) values ('eitmhpbv');